# 넘파이(Numpy)

넘파이(Numpy)는 수치 데이터를 다루는 파이썬 패키지이다. Numpy의 핵심이라고 불리는 다차원 행렬 자료구조인 ndarray를 통해 벡터 및 행렬을 사용하느 선형 대수 계산에서 주로 사용된다. Numpy는 편의성 뿐만 아니라, 속도면에서도 순수 파이썬에 비해 압도적으로 빠르다는 장점이 있다.

Numpy의 경우, 주로 np라는 명칭으로 임포트하는 것이 관례이다.

In [2]:
import numpy as np


#### Numpy의 주요 모듈

1. nparray() # 리스트, 튜플, 배열로부터 ndarray를 생성
2. np.asarray() # 기존의 array로부터 ndarray를 생성
3. np.arrange() # range와 비슷
4. np.linspace(start, end, num) # [start, end] 균일한 간격으로 num개 생성
5. np.logspace(start, end, num) # [start, end] log scale 간격으로 num개 생성

## 1) np.array()

numpy의 핵심은 ndarray다. np.array()는 리스트 튜플, 배열로부터 ndarray를 생성한다. 또한 인덱스가 항상 0으로 시작한다는 특징을 갖고 있다.

리스트를 가지고 1차원 배열을 생성해보자

In [4]:
a = np.array([1, 2, 3, 4, 5]) #리스트를 가지고 1차원 배열 생성
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


타입이 numpy.ndarray라고 나오고 있으며, 배열로 생성되었음을 알 수 있다.

이제 2차원 배열을 만들어보도록 하자.

한 가지 주의할 점은 array() 안에 하나의 리스트만 들어가므로 리스트의 리스트를 넣어야 한다.

In [8]:
b = np.array([[10, 20, 30], [ 60, 70, 80]]) 
print(b) #출력

[[10 20 30]
 [60 70 80]]


2차원 배열이 생성되었다. 행렬의 차원 및 크기를 ndim 속성과 shape 속성으로 출력할 수 있다.

In [9]:
print(b.ndim)
print(b.shape)

2
(2, 3)


위의 결과는 각각 2차원이며, 2X3 행렬임을 보여준다.

## 2) ndarray의 초기화

위에서는 리스트를 가지고 ndarray를 생성했지만, ndarray를 만드는 다양한 다른 방법이 존재한다. zeros()는 해당 배열에 모두 0을 삽입하고, ones()는 모두 1을 삽입한다. full()은 배열에 사용자가 지정한 값을 넣는데 사용하고, eye()는 대각선으로는 1이고 나머지는 0인 2차원을 생성한다.

In [10]:
a = np.zeros((2,3)) 
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
a = np.full((2,2),7) # 모든 값이 특정 상수인 배열 생성. 이 경우에는 7.
print(a)

[[7 7]
 [7 7]]


In [14]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
a = np.random.random((2,2))
print(a)

[[0.07987225 0.09588472]
 [0.86502982 0.53444607]]


## 3) np.arrange()

np.arrange()는 지정해준 범위에 대해서 배열을 생성해준다. np.arrange()의 범위 지정은 다음과 같다.

numpyy.arrange(start, stop, step, dtype)
a = np.arrange(n) # 0, ..., n-1까지의 범위 지정
a = np.arrange(i, j, k) # i부터 j-1까지 k씩 증가하는 배열

In [17]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

## 4) reshape()

In [19]:
a = np.array(np.arange(30)).reshape((5,6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


## 5) Numpy 슬라이싱

ndarray를 통해 만든 다차원 배열은 파이썬의 리스트처럼 슬라이스(Slice) 기능을 지원한다. 슬라이스 기능을 사용하면 원소들 중 복수 개에 접근할 수 있다.

In [20]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])

In [22]:
b = a[0:2, 0:2] # 각 차원별로 슬라이스 범위 지정
print(b)

[[1 2]
 [4 5]]


In [23]:
b = a[0, :] # 첫번째 행 출력
print(b)

[1 2 3]


In [25]:
b = a[:, 1] # 두번째 행 출력
print(b)

[2 5]


## 6) Numpy 정수 인덱싱(integer indexing)

정수 인덱싱은 원본 파일로부터 부분 배열을 구한다.

In [30]:
a = np.array([[1,2], [4,5], [7,8]])
b = a[[2, 1],[1,0]] # a[[row2, row1], [col1, col0]]을 의미함

In [31]:
print(b)

[8 4]


## 7) Numpy 연산

Numpy를 사용하면 배열간 연산을 손쉽게 할 수 있다. +,-,*,/의 연산자를 사용할 수 있으며, 또는 add(), subtract(), multiply(), divide() 함수를 사용할 수도 있다.

In [33]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [34]:
b = x + y # 각 요소에 대해서 더함
# b = np.add(x, y)와 동일함
print(b)

[5 7 9]


In [35]:
b = x - y # 각 요소에 대해서 빼기
# b = np.subtract(x, y)와 동일함
print(b)

[-3 -3 -3]


In [36]:
b = b * x # 각 요소에 대해서 곱셈
# b = np.multiply(b, x)와 동일함
print(b)

[-3 -6 -9]


In [37]:
b = b / x # 각 요소에 대해서 나눗셈
# b = np.divide(b, x)와 동일함
print(b)

[-3. -3. -3.]


위에서 *를 통해 수항핸 것은 요소별 곱이었다.

Numpy에서 벡터와 행렬의 곱 또는 행렬곱을 위해서는 dot()을 사용해야 한다.

In [38]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

c = np.dot(a, b)
print(c)

[[19 22]
 [43 50]]
